server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/auth/realms/tutorial-realm/protocol/openid-connect/auth 
            userinfo-uri: http://localhost:8180/auth/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/auth/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          tutorial-client:
            provider: keycloak
            client-id: tutorial-client
            client-secret: def75210-c1b4-46e9-8a68-4bc26f17fbf0
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"